### ISSUE TITLE
qliksense preflight --all

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/sense-installer#175]
- `qliksense preflight --all` // run all the check that preflight allowed so far

**Comment by ashwathishiva** [comment]
PR is here: https://github.com/qlik-oss/sense-installer/pull/240
Latest PR: https://github.com/qlik-oss/sense-installer/pull/263

**Comment by ashwathishiva** [comment]
latest PR: https://github.com/qlik-oss/sense-installer/pull/276
