### ISSUE TITLE
Create a one line install based on CR fed from stdin

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#201]
A one installation for non-git mode similar to `kubectl apply -f` in the case of applying a CR in git mode:

`qliksense install -f  CR.yaml` or `cat CR.yaml | qliksense install -f -` would fetch the version of qliksense-k8s specified in CR (latest if empty), create a new configuration context if one of the CR name does not exist, else update, create the patches, generate and install the manifest.

**Comment by ffoysal** [comment]
Validate the command `apply` if we still require to have in `install`
