### ISSUE TITLE
cli (non-git) mode should validate profile earlier on with a friendly message

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#224]
qliksense install --acceptEULA=yes v0.0.2
Installing operator controller
deployment.apps/qliksense-operator unchanged
role.rbac.authorization.k8s.io/qliksense-operator configured
rolebinding.rbac.authorization.k8s.io/qliksense-operator unchanged
serviceaccount/qliksense-operator unchanged
Installing resoruces used kuztomize patch
Installing generated manifests into cluster
Manifests root: C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2
2020/03/17 16:37:07 backing up keys to the cluster
cannot generate manifests for C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2\manifests\doesntexists evalsymlink failure on 'C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2\manifests\doesntexists' : CreateFile C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2\manifests\doesntexists: The system cannot find the file specified.
cannot do kubectl apply on manifests
Error: evalsymlink failure on 'C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2\manifests\doesntexists' : CreateFile C:\Users\DWB\.qliksense\contexts\mydefault\qlik-k8s\v0.0.2\manifests\doesntexists: The system cannot find the file specified.
Usage:
  qliksense install [flags]

Examples:
qliksense install <version> #if no version provides, expect manifestsRoot is set somewhere in the file system

Flags:
  -a, --acceptEULA string          AcceptEULA for qliksense
  -h, --help                       help for install
      --keep-config-repo-patches   Keep config repo patch files (for debugging)
  -m, --mongoDbUri string          mongoDbUri for qliksense (i.e. mongodb://qlik-default-mongodb:27017/qliksense?ssl=false)
  -r, --rotateKeys string          Rotate JWT keys for qliksense (yes:rotate keys/ no:use exising keys from cluster/ None: use default EJSON_KEY from env
  -s, --storageClass string        Storage class for qliksense

**Comment by ffoysal** [comment]
if manifestroots does not exist, install command also download it

**Comment by ffoysal** [comment]
if manifests roots does not exist, install command also download it

**Comment by ffoysal** [comment]
if manifests root does not exist, install command also download it
