### ISSUE TITLE
Allow CLI to operate as a kubectl plugin

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#33]
Use krew to install qliksense as a kubectl plugin.

**Comment by MoKassem** [comment]
@bearium can u please update me on this and whether we should close it or no? thx

**Comment by bkuschel** [comment]
Verified to work. Need to post plugin yaml as part of build.

**Comment by bkuschel** [comment]
https://github.com/qlik-oss/sense-installer/issues/132
