### ISSUE TITLE
Provide CLI operators for fetching qliksense-k8s, apply patches and generate manifest

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#34]
Provide the ability 

1. to fetch a version of [https://github.com/qlik-oss/qliksense-k8s/](https://github.com/qlik-oss/qliksense-k8s/)
2. Render the Operator YAML => [https://github.com/qlik-oss/qliksense-operator/issues/11](https://github.com/qlik-oss/qliksense-operator/issues/11)
3. If git.repo is not supplied in config, uses [Operator API](https://github.com/qlik-oss/qliksense-operator) to generate patches onto file system and render manifest in response to [a configured CR](https://github.com/qlik-oss/sense-installer/issues/32), creates association between CR and manifest => [https://github.com/qlik-oss/qliksense-operator/issues/12](https://github.com/qlik-oss/qliksense-operator/issues/12)
4. If git.repo is supplied in CR, CLI delegates patche creation and manifest generation to the [kubernetes controller](https://github.com/qlik-oss/qliksense-operator)

```shell
> kubectl qliksense install 1.0.0
  → kubectl qliksense fetch 1.0.0 # pull down qliksense-k8s@1.0.0
  → kubectl qliksense operator view | kubectl apply -f # operator manifest (CRD)
  → kubeclt qliksense config apply | kubectl apply -f # generates patches (if required) in configuration directory, applies manifest
  → kubectl qliksense config view | kubectl apply -f # generates Custom Resource manifest (CR)
```

**Comment by ffoysal** [comment]
```
 → kubectl qliksense operator view | kubectl apply -f # operator manifest (CRD)
  → kubeclt qliksense config apply | kubectl apply -f # generates patches (if required) in configuration directory, applies manifest
  → kubectl qliksense config view | kubectl apply -f # generates Custom Resource manifest (CR)
```
are done as part of #55

**Comment by ffoysal** [comment]
remaining command added in https://github.com/qlik-oss/sense-installer/pull/62

**Comment by ffoysal** [comment]
step 4 is going to be implemented in https://github.com/qlik-oss/sense-installer/issues/80
