### ISSUE TITLE
minimum porter version specified in dependencies.yaml has to support custom actions.

### ISSUE THREAD

**Issue by ashwathishiva** [qlik-oss/sense-installer#35]
The minimum porter version we have currently in `dependencies.yaml`: `0.2-beta-3-0e19ca4` does not support custom actions. So, it will fail to execute the 'about' and 'preflight' actions successfully. To overcome this shortcoming, we need to specify that version of porter as minimum version, that supports custom actions: `v0.22.1-beta.1`

**Comment by ffoysal** [comment]
fixed in https://github.com/qlik-oss/sense-installer/pull/23
