### ISSUE TITLE
Automatically fetch invocation image dependencies at runtime

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#7]
An invocation image will have the following dependencies:

- Minimum installer version
- the mixins used (during build)
- porter used (during build)

1. The cli will check a docker image metadata for version information for minimum installer version (if specified)
`org.qlik.operator.cli.min.version`

If the cli is lower than this version, it will exit saying that it's too old, and user should download `org.qlik.operator.cli.min.version` or greater

2. The cli will check a docker image metadata for version information for the minimum mixin version. Ex. qliksense mixin
`org.qlik.operator.mixin.qliksense.version.min`

The CLI will download the qliksense mixin version if the one used is less than `org.qlik.operator.mixin.qliksense.version.min`

This should be generalized for all mixins.

3. The cli will check a docker image metadata for version information for the minimum porter version. 
`org.qlik.operator.porter.version.min`

The CLI will download the porter version if the one used is less than `org.qlik.operator.porter.version.min`

**Comment by ashwathishiva** [comment]
thanks @bkuschel will look into this.

**Comment by ashwathishiva** [comment]
Please remember to house `dependencies.yaml` in the same location the qliksense installer is run from.

list of commands that work:
----------------------------
```
qliksense about
qliksense about --tag qlik/qliksense-cnab-bundle:v1.21.23-edge

qliksense preflight -c Qliksense
qliksense preflight --param namespace=test-ns -c Qliksense
qliksense preflight --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense
qliksense preflight --param namespace=test-ns --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense

qliksense build -v (run this from a dir containing porter.yaml)

qliksense install -c Qliksense -->   (default installation name will be `Qliksense`, pass this name during uninstall operation)
qliksense uninstall Qliksense -c Qliksense --> using default install name

qliksense install --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense
qliksense uninstall --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense

qliksense install --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense
qliksense upgrade -c Qliksense
qliksense upgrade --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense
qliksense uninstall --tag qlik/qliksense-cnab-bundle:v1.21.23-edge -c Qliksense
```

To enable debug support: 
--------------------------
```
export QLIKSENSE_DEBUG=true 
qliksense <command>
```
