### ISSUE TITLE
Use UPX to compress binary

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/sense-installer#88]
https://github.com/upx/upx/

**Comment by ibiqlik** [comment]
Small issue, upx binaries are not available in circleci's image circleci/golang:stretch.

I see 3 options
1. Make a docker build image (based circleci/golang:stretch) and use that in circleci
2. Add run command that fetches upx binaries as part of circleci job
3. Move to GitHub action (which have upx preinstalled)

Also the current build process makes archives (tar.gz) of the binaries but that would not be necessary if we use upx (same size)
